"""add phone number to post

Revision ID: 2d0909e263ff
Revises: 38ec787474df
Create Date: 2022-03-11 12:22:58.585101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0909e263ff'
down_revision = '38ec787474df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'phone')
    # ### end Alembic commands ###
