"""add owner

Revision ID: 38ec787474df
Revises: ff78edeb4a3e
Create Date: 2022-03-10 22:53:35.978308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ec787474df'
down_revision = 'ff78edeb4a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
