"""changes in posts again

Revision ID: ff78edeb4a3e
Revises: 726960cadcc4
Create Date: 2022-03-09 01:08:26.105655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff78edeb4a3e'
down_revision = '726960cadcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
